name: Leak Check

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install clang
      run: dpkg --list | grep compiler && apt update && apt-get install -y g++ clang && dpkg --list | grep compiler
      shell: bash
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - name: Checkout
      uses: actions/checkout@v4
    - name: Go Test
      env:
        CC: clang
        CXX: clang++
      run: |
        go test -c --tags leakcheck
        ./v8go.test
