name: V8 Build

on:
  workflow_dispatch:
  push:
    branches: ['v8_*_upgrade']
    paths: ['deps/VERSION']

jobs:
    build:
        name: Build V8 for ${{ matrix.platform }} ${{ matrix.arch }}
        strategy:
            fail-fast: true
            matrix:
                # We use macos-11 over macos-latest because macos-latest defaults to Catalina(10.15) and not Big Sur(11.0)
                # We can switch to macos-latest whenever Big Sur becomes the default
                # See https://github.com/actions/virtual-environments#available-environments
                #
                # We need xcode 12.4 or newer to cross compile between arm64/amd64
                # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xcode
                platform: [ubuntu-22.04, macos-latest]
                arch: [x64, arm64]
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: true
                  clean: true
                  fetch-depth: 1

            - name: Set v8 build name
              working-directory: ./deps
              run: ./v8_name.sh ${{ matrix.arch }}

            - name: Build Release for Linux
              if: startsWith(matrix.platform, 'ubuntu')
              uses: ./.github/actions/build-linux
              with:
                target-arch: ${{ matrix.arch }}

            - name: Build Release for macOS
              if: startsWith(matrix.platform, 'macos')
              uses: ./.github/actions/build-macos
              with:
                target-arch: ${{ matrix.arch }}

            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                name: ${{ env.ARCHIVE_NAME }}
                path: deps/v8/out/release/obj/libv8_monolith.a
                retention-days: 1

    release:
      runs-on: ubuntu-latest
      permissions:
        # Give the default GITHUB_TOKEN write permission to commit and push the
        # added or changed files to the repository.
        contents: write
      needs: build
      steps:
        - name: Download Archives
          uses: actions/download-artifact@v4
          with:
            path: artifact

        - name: Display Downloads
          run: ls -lhR artifact

        - name: Copy Artifacts to correct folders
          shell: bash
          run: |
            rm deps/darwin_x86_64/libv8.a
            rm deps/darwin_arm64/libv8.a
            rm deps/linux_x86_64/libv8.a
            rm deps/linux_arm64/libv8.a

            cp artifact/v8_darwin_x64.a deps/darwin_x86_64/libv8.a
            cp artifact/v8_darwin_arm64.a deps/darwin_arm64/libv8.a
            cp artifact/v8_linux_x64.a deps/linux_x86_64/libv8.a
            cp artifact/v8_linux_arm64.a deps/linux_arm64/libv8.a

        - name: Commit and Push
          uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: "Update V8 static libraries"
