name: V8 Build

on: workflow_dispatch

jobs:
    build:
        name: Build V8 for ${{ matrix.platform }} ${{ matrix.arch }}
        strategy:
            fail-fast: false
            matrix:
                # We use macos-11 over macos-latest because macos-latest defaults to Catalina(10.15) and not Big Sur(11.0)
                # We can switch to macos-latest whenever Big Sur becomes the default
                # See https://github.com/actions/virtual-environments#available-environments
                #
                # We need xcode 12.4 or newer to cross compile between arm64/amd64
                # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xcode
                platform: [ubuntu-22.04, macos-latest]
                arch: [x64, arm64]
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: true
                  clean: true
                  fetch-depth: 1

            - name: Build Release for Linux
              if: startsWith(matrix.platform, 'ubuntu')
              uses: ./.github/actions/build-linux
              with:
                target-arch: ${{ matrix.arch }}

            - name: Build Release for macOS
              if: startsWith(matrix.platform, 'macos')
              uses: ./.github/actions/build-macos
              with:
                target-arch: ${{ matrix.arch }}
